### ISSUE TITLE
Build out "Public information" pages

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#880] opened 2017-03-13 23:54 UTC
So that members of the public can find general information about what the FEC does, build out the pages for the "Public information" section.

---

This is for implementing the decisions from https://github.com/18F/fec-cms/issues/844

It may end up requiring additional components developed in the CMS, but it may be possible to do this all with existing components.

**Completion criteria:**
- [x] Build out all pages
- [ ] Link to it in the footer nav
- [ ] Link to it from the home page

**Comment by emileighoutlaw** [comment] 2017-03-22 21:24
So far, we're all feeling aligned that there are three main sections of content for this section and on what all the sub-pieces of those sections should be:

![screen shot 2017-03-13 at 2 49 58 pm](https://cloud.githubusercontent.com/assets/10552702/23872584/d6967cc4-07fc-11e7-9e79-01cda343e59a.png)

So we're ready to move to design next sprint :)

**Comment by noahmanger** [comment] 2017-03-22 21:26
Do we need to go through a design phase, or should we just jump to implementing within the CMS pages given existing modules?

**Comment by jenniferthibault** [comment] 2017-03-22 21:42
@noahmanger please hold off on CMS-ing for now, I'd like to think through it a bit, but I'm trying to concentrate on the orientation & two site experience epics first. I'll likely get to this on Friday, if that's ok.

I checked quickly with @emileighoutlaw and neither of us remembered a decision point about linking to this from the footer. How specifically folks get to it is still open, but loosely, it will be accessible from a link somewhere on the home page.

**Comment by jenniferthibault** [comment] 2017-03-24 21:43
These feel best to me in the templates we're going to use for the Candidate & committee services page (the ones that have the sibling content in the aside up top)

Observations: these three sections don't wuite feel like each other at the moment. I'm not quite sure how important that is, but it's super surprising to go from Getting involved, which is short, to Researching, which is suuuuuuper long.

**[Getting involved](https://cloud.githubusercontent.com/assets/11636908/24314556/97feb322-10b8-11e7-9640-d2c4f55d0e24.png)** 🔗 🖌 
- Do we want to bring any other brochure topics into their own content section? It feels slightly misleading to show filing a complaint as the "only" way to get involved 

**[Researching](https://cloud.githubusercontent.com/assets/11636908/24314557/99ae6668-10b8-11e7-9693-6b8898494395.png)** 🔗 🖌 
- This feels like it could use more/alternative structure. There's only one h2, so it doesn't break up well into a side menu

**[Voting & elections](https://cloud.githubusercontent.com/assets/11636908/24314560/9b2b7094-10b8-11e7-91aa-4ae761990540.png)** 🔗 🖌 
- This one feels like the structure fits the format pretty well!

To be figured out: how do people get to these pages? @emileighoutlaw any thoughts on if we do or don't need to gather these into one landing point?

**Comment by jenniferthibault** [comment] 2017-03-29 17:10
@emileighoutlaw and I chatted briefly this morning about this, and there's actually a pretty straight pathway to build these pages in to the current home page slab design:

- "Getting involved in the election process" has a lot of parity with the substance of the Citizens' guide brochure
  - ![screen shot 2017-03-29 at 12 06 10 pm](https://cloud.githubusercontent.com/assets/11636908/24464513/2061abee-1478-11e7-9ec5-c6c7c6adfa36.png)

- "Researching campaign finance data" has a great intro for folks looking to start learning about what's available and how they can use it, which pairs up with our first content item nicely
  - ![screen shot 2017-03-29 at 12 09 47 pm](https://cloud.githubusercontent.com/assets/11636908/24464718/af37bed0-1478-11e7-8e27-757d686eced4.png)


- "Information about voting and elections"  is a nice follow up to the final point about state-specific info
  - ![screen shot 2017-03-29 at 12 10 07 pm](https://cloud.githubusercontent.com/assets/11636908/24464721/b4955798-1478-11e7-850f-86db083f85c7.png)


@emileighoutlaw is going to continue thinking on the section title* but that comes together to make this:

![screen shot 2017-03-29 at 1 08 34 pm](https://cloud.githubusercontent.com/assets/11636908/24467019/de24aec6-1480-11e7-9bcd-dc71386bb84a.png)

**Remaining task:**
- Figure out how to get to these pages from pages other than the home page
  - *blocker:* content/IA strategy for this section?

**Comment by emileighoutlaw** [comment] 2017-03-30 22:55
I've long moaned about my poor naming skills 😭 — but do any of these feel like they're moving in the right direction, @jenniferthibault ?

> Introduction to campaign finance and elections
> Getting started with campaign finance and elections
> Beginner’s guide to campaign finance and elections

Strategy question: Do we need to resolve how we're getting to these pages from other pages _before_ we launch? I know we don't want them to be accessible only from the homepage long term, but is this something we're willing to do short-term? Or is that too big of a no-no :no_good_man: 🚫

**Comment by jenniferthibault** [comment] 2017-03-31 14:46
> Introduction to campaign finance and elections

would be my pick o' the litter 

If the content were complete and we had more confidence in how this section should work, I'd think we should make the IA plan holistically. But it's not/we don't, so I'd be ok with linking only from the home page for now as long as we open an issue to track the remaining plan.

**Comment by emileighoutlaw** [comment] 2017-03-31 14:48
That's my top choice too— do you think the next step is to schedule a meeting with Greg, George, and Jason and show them some things next week?

**Comment by jenniferthibault** [comment] 2017-04-11 13:38
Moved the home page link to a task in https://github.com/18F/fec-cms/issues/976

@emileighoutlaw do you want to keep this issue open for any other wagtail implementation issues, or close it?

**Comment by emileighoutlaw** [comment] 2017-04-19 14:40
Since Jason's confirmed we're solidly in last copyedits, I feel comfortable closing this issue and moving discussion to the implementation task. :)

**Closed by emileighoutlaw** 2017-04-19 14:40 UTC
Labels: Work: Content
