### ISSUE TITLE
Change "Full cycle" to "All Years" on candidate profile pages

### ISSUE THREAD

**Issue by PaulClark2** [18F/fec-cms#1444] opened 2017-11-03 17:08 UTC
So users understand what financial information is being presented, we should update "cycle" to "period" on candidate profile pages. 

The problem here is `cycle` has a very specific meaning. We are not aggregating by cycle. We are aggregating by calendar years.  As we all know, our financial summary numbers on the website do not match Column B numbers reported by authorized committees.

My preference is `Four-year period`, `Six-year period` and `Two-year period` instead of `cycle`.

website financial summary
![fec gov-financial-summary](https://user-images.githubusercontent.com/11817734/32386537-fcfee820-c097-11e7-9cf0-68c683de1103.jpg)

HTML representation of a report (see Column B amounts)
![html-presentation](https://user-images.githubusercontent.com/11817734/32386541-ff91db9c-c097-11e7-955a-3fe1cbc37eba.jpg)

**Comment by cptechiegal** [comment] 2017-11-07 23:26
fec.gov page: https://www.fec.gov/data/candidate/P80001571/

**Comment by cptechiegal** [comment] 2017-11-08 00:29
When filter for Time Period: 2017-2018 selected, 
https://www.fec.gov/data/candidate/P80001571/?cycle=2018&election_full=false
the filter page is getting a not found: 404 page

**Comment by PaulClark2** [comment] 2017-11-08 14:10
The  "cycle" change is needed on candidate profile pages of Senate and Presidential candidates.  The language change on candidate profile pages of House candidates is a little different. We need to change "time period" to "two-year period." 

https://www.fec.gov/data/candidate/P60022654/ (change "full cycle" to "four-year period"
![president](https://user-images.githubusercontent.com/11817734/32553055-cb6e7850-c463-11e7-9587-5c718b7cada9.png)

https://www.fec.gov/data/candidate/S6MD03177/ (change "full cycle" to "six-year period")
![senate](https://user-images.githubusercontent.com/11817734/32553075-dcc2b8d2-c463-11e7-8c3f-ec8c40c1a841.png)

https://www.fec.gov/data/candidate/H4VA10089/ (change "time period" to "two-year period')
![house](https://user-images.githubusercontent.com/11817734/32553211-33a8419e-c464-11e7-8cc7-171be02cb751.png)

**Comment by jenniferthibault** [comment] 2017-11-08 16:12
This also appears on the Candidates for President data table. Should we change it there too?

https://www.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true

<img width="304" alt="screen shot 2017-11-08 at 11 10 34 am" src="https://user-images.githubusercontent.com/11636908/32559638-a5338cb8-c475-11e7-995a-f1b4a37cef7b.png">

**Comment by PaulClark2** [comment] 2017-11-08 17:24
Yes, I think we should.  Is there a similar filter for Senate?

**Comment by jenniferthibault** [comment] 2017-11-08 17:29
Yes:

https://www.fec.gov/data/candidates/senate/?election_year=2018&cycle=2018&election_full=true
<img width="674" alt="screen shot 2017-11-08 at 12 29 28 pm" src="https://user-images.githubusercontent.com/11636908/32563923-86bb358c-c480-11e7-982f-d1cade022344.png">

**Comment by cptechiegal** [comment] 2017-11-22 19:58
@jenniferthibault  and @PaulClark2 
I reviewed this issue with @LindsayYoung and @patphongs today and they provided helpful input on possible solution logic to FEC-CMS code

1) For the primary change of the text: "Full Cycle" to the appropriate period for the Presidential and Senate Candidate Profile pages, we have logic to be added to accomplish this change.
Please note this change will affect all pages that have this "Full cycle" text.
The pages potentially impacted are as follows:
-candidate/financial-summary
-candidate/other-spending-tab
-candidate/about-candidate
-election-lookup  

2) The requested change to the House Candidate page to the "Time period" text  to "two-year period" would impact all screens that currently have the "Time period" text.  Alternatively, we would like to implement similar to the change to 1) above to display the  "two-year period" text in front of the min-max years and leave the "Time Period" text above it as is done for the other Candidate Profile pages.

3) The requested change to the Candidates for President data table (Edit Filters section)for "Full Cycle" to each type of period is still being reviewed researched.

**Comment by cptechiegal** [comment] 2017-11-25 01:32
1) candidate/other-spending-tab

https://fec-stage-proxy.app.cloud.gov/data/candidate/S6MD03177/?tab=other-spending


2) candidate/about-candidate

https://fec-stage-proxy.app.cloud.gov/data/candidate/S6MD03177/?tab=about-candidate

3)election-lookup

https://fec-stage-proxy.app.cloud.gov/data/elections/house/DC/00/2018/
probably not applicable?

**Comment by PaulClark2** [comment] 2017-11-27 13:23
@cptechiegal We will want to change "election cycle" to "two-year period" on the election pages:
- https://www.fec.gov/data/elections/house/DC/00/2018/
- https://www.fec.gov/data/elections/senate/CA/2018/
- https://www.fec.gov/data/elections/president/2016/

The financial summary amounts on these pages are two-year period summaries not cycle summaries.

**Comment by cptechiegal** [comment] 2017-11-28 23:52
Hi @paul please open a separate issue for this additional work request and assign to me as:
change "election cycle" to "two-year period" on the election pages:
https://www.fec.gov/data/elections/house/DC/00/2018/
https://www.fec.gov/data/elections/senate/CA/2018/
https://www.fec.gov/data/elections/president/2016/
The financial summary amounts on these pages are two-year period summaries not cycle summaries.

**Comment by PaulClark2** [comment] 2017-11-29 00:24
@cptechiegal you should create the GitHub ticket and assign it to yourself. I'm not sure I'm clear why this needs an additional ticket.

**Comment by jenniferthibault** [comment] 2017-11-29 03:02
### On the full cycle > X-year cycle change
Question. From @cptechiegal's [comment](https://github.com/18F/fec-cms/issues/1444#issuecomment-346458109) I understand that the logic is complicated for these changes, and we're actually talking about changing a few templates with complicated logic. So given that it's not exactly a straightforward fix to implement Paul's first suggestions, I want to raise an additional UX concern. But don't worry! I have a possible solution to go with it.

We're having to make complicated logic changes in a few places because our concise, but generic text is possibly misleading (if not, just not specific enough). 

**Problem:**
For places where we use `Full cycle: yyyy-yyyy`, we've intentionally used the collector word `Full` to communicate that the first toggle button is the data for the _entire_, _full_ increment of time that the following toggles break down into smaller chunks. Not only is it short, but it also unified the time. I'm worried that `_____-year cycle: yyyy-yyyy` not only is longer (and bad from a text scanning and comprehension perspective) but it also doesn't have the gathering/grouping effect that we had before.
<img width="670" alt="screen shot 2017-11-28 at 9 40 33 pm" src="https://user-images.githubusercontent.com/11636908/33355624-3b6209e2-d486-11e7-8896-9309c756fe00.png">


**Idea:**
Instead of replacing `Full cycle` with a longer string, could we instead replace just the problematic word, `cycle` with `period`? To be more accurate, but still concise + collective, we could use `Full period: yyyy-yyyy`

I'm thinking this because it would simplify the logic, and be shorter/more scannable. 

<img width="661" alt="screen shot 2017-11-28 at 9 53 15 pm" src="https://user-images.githubusercontent.com/11636908/33355660-6049fa1c-d486-11e7-8795-597f7d97c050.png">

_________________________

### On changing `time period` to `x-year period`
From Paul's screenshot above:
<img width="349" alt="screen shot 2017-11-28 at 9 54 58 pm" src="https://user-images.githubusercontent.com/11636908/33355724-aa82bff6-d486-11e7-8522-d491cf625d47.png">


From @cptechiegal 's comment above, I'm understanding that the suggestion is to pre-pend the year with `x-year period` in order to avoid some complex logic, which would look like the following:

<img width="482" alt="screen shot 2017-11-28 at 9 57 16 pm" src="https://user-images.githubusercontent.com/11636908/33355814-1489bdf0-d487-11e7-95f0-4f3312ead390.png">


@PaulClark2 can you help us understand if it is really inaccurate and problematic to use "Time period` here as it is without addition? Wondering if it's worth introducing complex logic, or a workaround that needs to happen because complex logic is too complicated (as described in Cristl's proposal) or if we could just leave it as is, minus some in-the-weeds specificity. 

______
Overall +1 to @cptechiegal's suggestion of breaking this into smaller issues once we have agreement on approach, since there are indeed a few different types of logic & changes being discussed.

**Comment by PaulClark2** [comment] 2017-11-29 18:59
I'm short on time before I leave for vacation, my preference is x-year period. This was the negotiated language we used in the Candidate and Committee Viewer.  I'm going to tag @AmyKort  and @jwchumley so this issue doesn't have to wait for me to get back.

**Comment by AmyKort** [comment] 2017-11-29 19:21
@PaulClark2  Do you hate "aggregated" or something to that effect? What if we put"time period" as the label over something like "2017-2018"(https://www.fec.gov/data/elections/house/DC/00/2018/)  but instead of saying "Full cycle" in the box on a candidate's page, we said "Aggregated: 2017-2020"  and then had the breakdown for 2017-2018, 2019-2020 follow that, since it really is just the aggregate of those 2-year time periods?

**Comment by PaulClark2** [comment] 2017-11-29 19:59
I don't hate it, but I do like x-year period better. Please run "aggregated" by Press and Public Records. They will get the questions from the public about the term.

**Comment by AmyKort** [comment] 2017-11-29 20:19
Will do. I'm interested in @jenniferthibault 's opinion about whether this is a workable solution, before we go further.

**Comment by cptechiegal** [comment] 2017-11-30 00:04
There are several change requested now on this issue.
Just to summarize my understanding so far on changes needed:
A) On the full cycle > X-year period change
1) Original request was to change the filter text on the Candidate Profile pages 
from: full cycle to: x-year period
Currently only the full period gets the prefix: full cycle 
Jen suggested changing the text from: full cycle to: full period

The change impacts these types of screens since there is a common template (cycle_select) involved:
a)candidate/financial-summary==>Candidate Profile pages
examples: Presidential
https://www.fec.gov/data/candidate/P60022654/
Senate 
https://www.fec.gov/data/candidate/S6MD03177/ 

b)Candidate/other-spending-tab
https://fec-stage-proxy.app.cloud.gov/data/candidate/S6MD03177/?tab=other-spending

c)Candidate/about-candidate
https://fec-stage-proxy.app.cloud.gov/data/candidate/S6MD03177/?tab=about-candidate


B)On changing time period to x-year period
The HR Candidate Profile/Financial Summary page differs from the others
since it does not show for the full 2 year period the text: full cycle  
https://www.fec.gov/data/candidate/H4VA10089/
Changing the text label above the period from: Time Period to: x-year period
would impact other screens mentioned above in part A) and therefore we suggested an alternate to add the prefix as was done on other full cycle/periods.
In this case the prefix could be: X-year period
Jen suggested that the prefix be: Full period

C) Additional request change to the Candidates for President data table (Edit Filters section)
from: "Full Cycle" to : X-year period
https://www.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true
This seems to be using the elections_filter common template.
(needs more research on impact)

D) Additional request change to the Election lookup pages
change "election cycle" to X-year period on the election pages
The financial summary amounts on these pages are two-year period summaries not cycle summaries.
https://www.fec.gov/data/elections/house/DC/00/2018/
https://www.fec.gov/data/elections/senate/CA/2018/
https://www.fec.gov/data/elections/president/2016/

Changing the label text above from: "election cycle" to X-year period
will impact other screens since this is another common template(election_cycle_select).
if changed, it will impact additional screens:
a) elections/candidate-comparison-tab
b) elections/detailed-comparison-tab
Possibly an alternate implementation is to add instead a prefix to the pulldown menu text.
In this case the prefix could be: X-year period
Jen suggested that this not be changed.
Amy suggested that the prefix be: Aggregated

**Comment by PaulClark2** [comment] 2017-11-30 17:10
Passing time in an airport....finishing up at my hotel

@jenniferthibault `time period` seems overly vague to me. We are aggregating financial data from two calendar years, four calendar years and six calendar years. If we know this, why be vague with a phrase like `time period`? Using `x-year period` also avoids confusing more sophisticated users that know candidate reporting requires election-cycle aggregation not calendar-year aggregation.

A little background on out two-year financial aggregations, prior to the Bipartisan Campaign Reform Act of 2002 (BCRA) candidates were required to report calendar-year aggregations. BCRA changed this requirement to election-cycle-to-date aggregations. In addition, an election cycle was defined as the day after a general election through the day of a general election. For example, the 2020 presidential election cycle started 11/09/2016 and ends 11/3/2020. Our financial aggregations and summaries from 1977 through 2002 were two-calendar-year summaries. To provide comparable data across time, FEC decided to continue producing two-calendar-year aggregations and summaries of campaign finance data.

If you compare a house, presidential or senate candidate’s authorized committee’s Column B (election-cycle-to-date) amounts to our two-year, four-year or six-year totals they will not be the same. We need to acknowledge that in a clear and meaningful way. 

@AmyKort thinking about “aggregated” more, I still don’t hate it. But, I don’t like it. Like I mentioned before. I think we need to check with the Press and Public Records.

Now I’m done until I’m back from my vacation.

**Comment by jenniferthibault** [comment] 2017-11-30 23:21
James, Jeff, Cristl, Amy and I are going to sync up tomorrow and work through this. That's a lot of brains, so I wanted to make sure we have a place to work together.

To plot out all the options we've talked about, I made a [Mural.ly workspace](https://app.mural.ly/t/gsa6/m/gsa6/1512080429283/967ceb101c180e57c74839814f9bbd09b190720e) where we can work & think through this. It focuses on the profile and election summary pages because 1) I ran out of room; and 2) I think decisions there will be the same solutions for the filters on the data tables.

**Comment by PaulClark2** [comment] 2017-12-01 02:58
I may have misunderstood @jenniferthibault ‘s suggestion from two days ago (https://github.com/18F/fec-cms/issues/1444#issuecomment-347738119). The mural.ly helped me understand that suggestion. 

I think modifying my original suggestion for House candidates to what Jen has suggested above for House candidates makes sense.  This change addresses my concerns about being clear that the aggregations presented on all the candidate profile pages are different from the aggregates disclosed in Column B of authorized committees’ reports. Hopefully replacing my original “House” suggestion with Jen’s suggestion simplifies the coding logic. 

![0b674c41-278e-4854-a941-be2150c22797](https://user-images.githubusercontent.com/11817734/33465728-0d651fa2-d652-11e7-9ed1-1a64b80448c6.jpeg)

Replace my House suggestion with Jen’s
![cfba8ae5-94fa-4082-a4b4-d68be1386f6b](https://user-images.githubusercontent.com/11817734/33465787-6dec331a-d652-11e7-9333-73f0f4cfb6dd.jpeg)

**Comment by jenniferthibault** [comment] 2017-12-01 15:58
Had a great session this morning, where we decided to pursue a few things:

1. Investigating how we'd improve the design of the `cycle_select` template toggles to make it more clear that you're choosing a total or subset amount of time to look at. Plain language will continue to be a part of this, as we pursue a solution that's clear to expert users, but not overcomplicated to the wider general audience. When we have a better concept, we'll shop it around with Press and Public record folks.

- This work will appear on candidate profile pages, and in the filters for President, Senate, and House filings data tables.
- That design work will happen in a new issue --> (to come)

2. Pursuing the change of label from "Election cycle" > "Two-year period" on election summary pages to clarify up front that you can't select more than two years to look at anyways. 

- We need to check the template partials to see which pages this change would impact
- We're going to split work around that into a new issue --> (to come)

_Will return to update this issue with links to the new ones once I've created them_

**Comment by jenniferthibault** [comment] 2017-12-08 23:14
In https://github.com/18F/fec-cms/issues/1613 we've been working on a more holistic design fix for  this interaction, but agreed that the immediate fix in the meantime is to change "Full-cycle: yyyy–yyyy" to "All years: yyyy–yyyy" in the toggle field, in order to squash the incorrect use of "cycle" but keep the implied totaling.

This looks like it applies to the following files, which populate the candidate profile pages and office-specific candidate data table filters :
- `fec/fec/tests/js/cycle-select.js`
- `fec/fec/static/js/templates/electionCycles.hbs`
- `fec/fec/static/js/templates/election-cycles.hbs`

@cptechiegal would you be up for picking this up again to complete the original purpose of this issue, since it was assigned to you before we dug into the complexity? If not, we could wait to discuss in sprint planning on Tuesday.

**Comment by cptechiegal** [comment] 2017-12-08 23:46
Hi @jenniferthibault 
Yes, I would like to continue the work on this issue now that the design team has found a good alternative wording for now.  I would like to see it get into next week's release along with related issue for addressing the 'cycle' terminology: 1605 (as well as the template cleanup issue 1632) .

**Comment by cptechiegal** [comment] 2017-12-12 18:05
New item 5. to this list of changes:
In researching the Candidate Profile pages for this issue, it was also noted that for both the Spending and Raising subpages the Elections pulldown component is displaying with  following issues:
a) The Elections component differs from other pages in that is does not include the Time Period sub component.
This type of page / screen should have both Election and Time Period components
- Change to the template for Elections that includes the Time Period subcomponent (cycle_select template)
b) The Elections pulldown component label contains the word 'cycle' which is no longer desirable wording for Election periods.
- The text will change automatically to only show 'Election' when the component's template is updated in part a) for using different a template that includes the time periods subcomponent.

**Comment by cptechiegal** [comment] 2017-12-13 21:21
Changes Completed:
1.  Changed the Candidate Profile pages
After design discussions this month, the final decision was to change the text from: "full cycle"
to: "All Years"
Manual Testing:
a)candidate/financial-summary==>Candidate Profile pages
Presidential
https://www.fec.gov/data/candidate/P60022654/
Senate
https://www.fec.gov/data/candidate/S6MD03177/
b)Candidate/other-spending-tab
https://www.fec.gov/data/candidate/S6MD03177/?tab=other-spending
c)Candidate/about-candidate
https://www.fec.gov/data/candidate/S6MD03177/?tab=about-candidate


2. Changed the Candidates for President data table (Edit Filters section)
pulldown menu label text from: "Full Cycle" to : “All Years”
Manual Testing:
https://www.fec.gov/data/candidates/president/?election_year=2016&cycle=2016&election_full=true

3. Changed the Election lookup pages
Changed the text label above the period from: "Election Cycle" to: "2-year period"
see separate issue --> #1605

4. Raising and Spending pages
Changed the label text for the heading on the Elections pulldown menu from ‘Election Cycle’ to ‘Election’
Manual Testing:
https://www.fec.gov/data/candidate/H8WI01024/?tab=raising
https://www.fec.gov/data/candidate/P80001571/?tab=raising
https://www.fec.gov/data/candidate/S2MA00170/?tab=raising
https://www.fec.gov/data/candidate/S2MA00170/?tab=spending

5. Review and Update Help 'Term' and No Data pages that use the term ‘Cycle'
 Separate Issue# https://app.zenhub.com/workspace/o/18f/fec-cms/issues/1646
Reviewed and closed by Amy as terminology correct as is.

Other Items / Not Addressed yet
1. House of Representatives (HR) Candidate Profile pages- 
Request for change on the label text from 'time period' to '2-year period'
Technical: This impacts the cycle-select template 
This is a common macro also used by all candidate pages.  
Instead, possibly make a new macro with this text change or use an existing macro, i.e., election_cycle_select, that has the 2-year period text (now since changed as part of issue#1605)

Reference:
https://www.fec.gov/data/candidate/H4VA10089/

2. House of Representatives (HR) Candidates Edit Filters / Data Table
Ref: https://www.fec.gov/data/candidates/house/
Discuss if any change is desired for the label text 'Election Cycle' 
Proposal: changing to the text 'Election two-year period'
![Election 2-year period pull down menu.jpeg](https://images.zenhubusercontent.com/597914ce61b4ca3b0a75d5ec/de01cf97-7553-4477-8a0d-b95d7aac99b3)
Amy prefers to wait for @PaulClark2  to review and decide on this item.

3. Raising and Spending pages
Proposed change by Design team to the Elections pulldown component 
by included the 'Time Period' subcomponent on the Raising and Spending pages
Separate issue# https://app.zenhub.com/workspace/o/18f/fec-cms/issues/1647


4. Review and change Code (i.e., refactor) to better align with the Design change from ‘election cycle’ to ‘election period’.
Proposal for technical discussion to change / refactor the use of the ‘Cycle’ term to ‘Period’ in the code to be consistent with Design

**Comment by cptechiegal** [comment] 2017-12-13 23:51
https://github.com/18F/fec-cms/pull/1652

**Comment by PaulClark2** [comment] 2017-12-29 13:42
For the filter, let's use `Two-year period` 

For now, let's leave the shared label, `Time period`, as it is.

**Comment by cptechiegal** [comment] 2017-12-29 17:14
Just to clarify, per @PaulClark2 
- No change required for the House of Representatives (HR) Candidate Profile pages-
leave the label text of 'time period' (i.e, don't change to: '2-year period')
- Proceed with Change:
 House of Representatives (HR) Candidates Edit Filters / Data Table page
Change the Filter label text from: 'Election Cycle'
to: 'Election two-year period'
Ref: https://www.fec.gov/data/candidates/house/

**Closed** 2018-01-04 18:04 UTC
Labels: Work: Front-end
