### ISSUE TITLE
Train content managers to use Wagtail

### ISSUE THREAD

**Issue by emileighoutlaw** [18F/fec-cms#631] opened 2016-12-05 23:21 UTC
To get our content managers creating Wagtail pages for our compliance, we need to train them how to do this. 

This will be complete when our managers can:
- [ ] Create custom pages
- [ ] Edit custom pages

**Comment by adrianwebb** [comment] 2016-12-06 20:23
Duplicate of: https://github.com/18F/fec-transition/issues/35

**Closed by adrianwebb** 2016-12-06 20:23 UTC
Labels: Dashboard: Content migration, Needs grooming, Work: Content
