### ISSUE TITLE
Candidate search not returning data

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1511] opened 2017-11-21 14:36 UTC
Users who look up Senate Candidates through https://www.fec.gov/data/candidates/senate/?election_year=2018&cycle=2018&election_full=true and select a particular candidate by name or ID number don't find any data to click on when they get their search results back. This seems to be a problem with the Senate Candidate look up only.   This is a good example: https://www.fec.gov/data/candidates/senate/?q=S8MN00438&election_year=2018&cycle=2018&election_full=true. 

The bug isn't consistent across all candidates ( https://www.fec.gov/data/candidates/senate/?q=warren&election_year=2018&cycle=2018&election_full=false ).

**Comment by jwchumley** [comment] 2017-11-28 18:52
Jeff- look at some examples to make sure the data should be there. Find some more examples.

**Comment by patphongs** [comment] 2017-11-28 18:55
@lbeaufort It appears to be a 502 in the API call: https://api.open.fec.gov/v1/candidates/?candidate_id=S8MN00438&api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ

**Comment by lbeaufort** [comment] 2017-11-28 19:56
@patphongs it looks like maybe that 502 was related to the API issues we were having. Can you confirm please?

**Comment by jwchumley** [comment] 2017-12-12 18:39
@jwchumley

**Comment by jwchumley** [comment] 2017-12-13 17:37
Closing this because it is working as designed. If you select an election year then you see only candidates in that election year. Might revisit this later if there is continuing confusion.

**Closed by jwchumley** 2017-12-13 17:37 UTC
Labels: Bug
