### ISSUE TITLE
Withdrawn AO issue

### ISSUE THREAD

**Issue by patphongs** [18F/fec-cms#1390] opened 2017-10-26 14:45 UTC
It appears that a few withdrawn AOs are not showing up as withdrawn within the `Date issued` column. These AOs include AO 2017-11 and AO 2009-05.

https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=W

- [x] Verify that ao.stage data maps to AO status (0 = pending, 2 = withdrawn, 1 = final)
- [X] Replace AO `is_pending` with with `ao_status`
- [X] Verify searches still work in API where `ao_category=W`
- [x] Test AO search with `status` parameter

- [x] CMS - change logic for display date for withdrawn AO's to check AO status, not date = 1/1/1900. This was providing unreliable data.
- [X] Test AO 2009-05
- [x] Test AO 2017-11 

Thanks @vrajmohan for your help!

**Comment by lbeaufort** [comment] 2017-11-01 20:53
@patphongs I think I'm on to something with 2017-01, but when I look for 2009-05, it shows up for me. Can you take a look? I want to make sure I'm understanding the issue. 

https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=W&ao_no=2009-05

**Comment by lbeaufort** [comment] 2017-11-02 14:15
Looks like the logic here is the cause: https://github.com/18F/fec-cms/blob/develop/fec/fec/static/js/legal/SearchResults.js#L15

**Comment by lbeaufort** [comment] 2017-11-02 16:22
Currently, the AO endpoint has a boolean `is_pending` parameter, but no category for "Final" or "Withdrawn." Documents within the AO have categories, though. I'm asking Vraj the best way to address the gaps in the logic above ^^

**Comment by lbeaufort** [comment] 2017-11-03 16:10
It looks like in the database, the `stage` field corresponds with AO status above. However, one withdrawn AO (2009-05) seems to have been marked Final in the internal database. We can capture those outliers by including AO's with "Withdrawn" in the summary: `select ao_no, stage, * from aouser.ao where stage=2 OR ao.summary LIKE 'Withdrawn%';`

**Comment by vrajmohan** [comment] 2017-11-03 17:12
Unless there is diligence over the AO summary, `ao.summary LIKE 'Withdrawn%'` seems to be a very wide net.

**Comment by lbeaufort** [comment] 2017-11-03 17:52
@vrajmohan I agree - I don't like programming around inconsistent data. Maybe a better option would be to explore updating the data on our end so Stage = `Withdrawn` instead of `Final` for AO 2009-05

**Comment by lbeaufort** [comment] 2017-11-03 19:58
Agreed-upon solution is to hard-code the withdrawn AO that is marked as final in the database until its stage can be changed to withdrawn in the database. 

 `select ao_no, stage, * from aouser.ao where stage=2 OR ao_no='2009-05';`

**Closed** 2017-11-13 17:10 UTC
Labels: Bug
