### ISSUE TITLE
Update handlebars in Swagger API docs

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#1490] opened 2017-11-14 16:14 UTC
Here is where the package is
https://github.com/18F/swagger-ui/blob/master/package.json#L39

(I am adding the issue in this repo so it doesn't get lost It won't show up on all the boards if it is in the swagger repo)

**Comment by patphongs** [comment] 2017-11-27 16:13
Seems to be a duplicate of https://github.com/18F/fec-cms/issues/1491. Closing...

**Closed by patphongs** 2017-11-27 16:13 UTC
Labels: Bug, Urgent
