### ISSUE TITLE
Visual design of Resources for Media Professionals page

### ISSUE THREAD

**Issue by jenniferthibault** [18F/fec-cms#480] opened 2016-09-06 20:13 UTC
Carries over interaction designs from https://github.com/18F/fec-cms/issues/455

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by emileighoutlaw** [comment] 2016-09-06 21:23
Let me know if you need me to recap any content decisions here, Jen <3

**Comment by jenniferthibault** [comment] 2016-09-06 21:53
Glad you pinged @emileighoutlaw :smile: Based on [this doc](https://docs.google.com/document/d/1-WtXMrJ3zPIm1f5Bz441lyR45RyY6Uvw6ydk3huLnq0/edit#) we do in fact have some outstanding content needs for this page.

There are a few places where we've left placeholder content that I'm not seeing real content for, and marked those.

I also tried to mark out the page's structure in there, because I was having a hard time telling what pages were supposed to be individual links. 

Hope I didn't just make a giant mess, but everything is in suggesting mode to try and keep it from being destructive!

**Comment by nickykrause** [comment] 2016-09-06 22:02
@jenniferthibault @emileighoutlaw 

Some of the confusion here might be caused by me...when I was putting the wires together, I was scrolling through the Google Doc trying to get a sense of what the page architecture would be, in terms of main sections/subsections, and I don't think it was entirely consistent with @emileighoutlaw's document.

Also, I believe @emileighoutlaw was still in the process of determining which pages could be consolidated, and I'm not sure where she landed

Anyway, apologies if I misled you, @jenniferthibault!

**Comment by jenniferthibault** [comment] 2016-09-07 14:22
Oh that makes more sense now! No worries @nickykrause - this is just the right time to pull that all together into the finished first draft.

**Comment by emileighoutlaw** [comment] 2016-09-08 02:30
No need to apologize @nickykrause ! This is my fault for not surfacing this more clearly and sooner!

The outline has 19 distinct pages. I initially felt like that was a lot, but I went back and counted for `Candidates and committees

> ## Agency overview
- Commissioners
- Commission meetings
- Advisory opinions
- Litigation involving the FEC
- Strategic Plans, budget documents and Performance and Accountability Reports from Fiscal Year 2004 to present are available on FEC.gov


Campaign finance law
The FEC has exclusive jurisdiction over the civil enforcement of federal campaign finance law. The Commission does not have authority over criminal enforcement.

FEC’s response to violations 
Review of campaign finance reports
Administrative Fine Program
Audits

FEC enforcement programs
Complaints
Matters Under Review (MURs)
Alternative Dispute Program

Fundraising and contributions
Fundraising
Joint fundraising
Selling or raffling items for fundraising purposes
Contributions
Prohibited sources of contributions
In-kind contributions
Earmarked vs. bundled contributions



About candidates and committees
Registration and reporting
The role of committee treasurers
    
Candidates for president, Senate and House
Personal financial disclosures
Political action committees (PACs)
Political party committees
Convention committees and host committees
Inaugural committees

Tax exempt status for committees
Presidential public funding


Public and coordinated communications
Public communications
Independent expenditures
Electioneering communications
Disclaimers
Coordinated communications



Notes

**Comment by emileighoutlaw** [comment] 2016-09-08 03:00
No need to apologize @nickykrause ! This is my fault for not surfacing this more clearly and sooner! 


# Intro
I'm going to do my best to explain this clearly and succinctly, but let me know after you've read this what is still muddy.

The outline has 19 distinct pages. (I initially felt like that was a lot, but I went back and counted for our `Registration and reporting` : `Candidates and committees`  section, and that has 17 distinct pages. Additionally, I think we're moving toward minimalism as we iterate here— I believe this will only shrink with time, not expand)

This checklist has  5 main sections: 
- `Agency overview`
- `Campaign finance law`
- `Fundraising and contributions`
- `About candidates and committees`
- `Public and coordinated communications`

Some of these sections have an intro blub, and some do not. I've waffled on whether I want to create more content (for consistency), which would mean more for journalists to slog through. ¯\_(ツ)_/¯


# The checklist 

> ## Agency overview
- Commissioners
- Commission meetings
- Advisory opinions
- Litigation involving the FEC
- Strategic Plans, budget documents and Performance and Accountability Reports from Fiscal Year 2004 to present are available on **FEC.gov**(link)

_note: the last bullet goes to an FEC.gov page, not a checklist page_

> ## Campaign finance law
_The FEC has exclusive jurisdiction over the civil enforcement of federal campaign finance law. The Commission does not have authority over criminal enforcement._

> - **FEC’s response to violations** 
    - Review of campaign finance reports
    - Administrative Fine Program
    - Audits

> - **FEC enforcement programs**
    - Complaints
    - Matters Under Review (MURs)
    - Alternative Dispute Program

_note: There are only two distinct checklist pages here— one for `violations` and one for `enforcement`. The sub-bullets are sections of those pages. I surfaced them in the checklist because we can anchor link them to the appropriate section header on the `enforcement` or `violation` page, and I believe that journalists (who are looking for the best information the fastest) will be scanning the pages for these specific program names. This is a pattern you'll see in other sections to follow._

_As you keep reading this outline (so I don't have to keep making notes about this), all of the white circle bullets represent content that's located **inside** its parent page. Only the black bullets represent distinct checklist pages._


> ## Fundraising and contributions
- Fundraising
    - Joint fundraising
    - Selling or raffling items for fundraising purposes
- Contributions
    - Prohibited sources of contributions
    - In-kind contributions
    - Earmarked vs. bundled contributions

> ## About candidates and committees
- Registration and reporting
    - The role of committee treasurers
- Candidates for president, Senate and House
    - Personal financial disclosures
- Political action committees (PACs)
- Political party committees
- Convention committees and host committees
- Inaugural committees
- Tax exempt status for committees
- Presidential public funding

> ## Public and coordinated communications
- Public communications
    - Independent expenditures
    - Electioneering communications
    - Disclaimers
- Coordinated communications


# [ END CHECKLIST ]


# Concluding notes
I've been trying to condense and re-architect this for a week now, and despite my best efforts, there are still things here that really aren't ideal from a content standpoint. That said, I do believe this gives us something tangible to start testing. And something better than what they have on FEC.gov.

Also, in many ways, I think the fact that this content  _will look as expansive as it is_ in the checklist format will help us make a case for paring it down (if we find in testing that that's what we should do). 



# The checklist (again)
The last outline was pretty broken up by my notes, so I'm pasting it here again, uninterrupted:



> ## Agency overview
- Commissioners
- Commission meetings
- Advisory opinions
- Litigation involving the FEC
- Strategic Plans, budget documents and Performance and Accountability Reports from Fiscal Year 2004 to present are available on **FEC.gov**(link)


> ## Campaign finance law
_The FEC has exclusive jurisdiction over the civil enforcement of federal campaign finance law. The Commission does not have authority over criminal enforcement._

> - **FEC’s response to violations** 
    - Review of campaign finance reports
    - Administrative Fine Program
    - Audits

> - **FEC enforcement programs**
    - Complaints
    - Matters Under Review (MURs)
    - Alternative Dispute Program


> ## Fundraising and contributions
- Fundraising
    - Joint fundraising
    - Selling or raffling items for fundraising purposes
- Contributions
    - Prohibited sources of contributions
    - In-kind contributions
    - Earmarked vs. bundled contributions

> ## About candidates and committees
- Registration and reporting
    - The role of committee treasurers
- Candidates for president, Senate and House
    - Personal financial disclosures
- Political action committees (PACs)
- Political party committees
- Convention committees and host committees
- Inaugural committees
- Tax exempt status for committees
- Presidential public funding


> ## Public and coordinated communications
- Public communications
    - Independent expenditures
    - Electioneering communications
    - Disclaimers
- Coordinated communications

**Comment by emileighoutlaw** [comment] 2016-09-08 03:38
Oh! And one more thing. If we think that the checklist in my preceding comment ^^ looks too expansive, I had been toying with another way of explaining what's in each page, other than with sub-bullets. That could look really roughly like this:


> ## Public and coordinated communications
- **Public communications**: _including independent expenditures, electioneering communications and disclaimers_
- **Coordinated communications**


OR like this

> ## Public and coordinated communications
- **Public communications**

>    _Including independent expenditures, electioneering communications and disclaimers_
- **Coordinated communications**


Or something else (you visual and interaction wizards always have better ideas than I do on this front 😄)

**Comment by jenniferthibault** [comment] 2016-09-08 14:48
@emileighoutlaw thanks so much for sorting this out so clearly! One thing I particularly hadn't  understood before was that the white bullets were _not_ their own pages.  I get it now!

I really like your suggestion to condense those white bullets into one line. I kept the links to each sub-section in this mockup, because that functionality seems useful, as you said. Making those sections into one line helps with the page length, and makes it more clear that they aren't separate pages:

<img width="427" alt="screen shot 2016-09-08 at 10 43 14 am" src="https://cloud.githubusercontent.com/assets/11636908/18353827/83e2957c-75b1-11e6-9602-50ccc59e8437.png">


Last question. Do you want to use the copy space at the top of the page that's still lorem ipsum? We don't have to, but if we take it out, I'd probably remove the "More resources" right-hand box and instead turn those elements into cards at the bottom of the page.

<img width="862" alt="screen shot 2016-09-08 at 10 47 28 am" src="https://cloud.githubusercontent.com/assets/11636908/18353912/c5e877a2-75b1-11e6-8dbf-9fec35e44731.png">

**Comment by emileighoutlaw** [comment] 2016-09-08 18:40
I love the way you've styled the "including" sections! Thank you! I knew there was visual design wizardry that would solve all my problems!


Great question about the lorem ipsum. I think we should reuse whatever we decide on for the `Resources` introductory paragraph on the `Press` homepage. I'm working on that in this issue: https://github.com/18F/fec-cms/issues/481#issuecomment-245627657

I'll update here when we have something to move forward with. Heads up that it seems more likely to be 1-2 sentences, as opposed to 2 paragraphs.

**Comment by noahmanger** [comment] 2016-09-12 21:54
Visual design not only finished but implemented.

**Closed by noahmanger** 2016-09-12 21:54 UTC
Labels: Dashboard: Design
