### ISSUE TITLE
Additional text cleaning on data import

### ISSUE THREAD

**Issue by LindsayYoung** [18F/fec-cms#498] opened 2016-09-16 14:10 UTC
This will be on-going but this ticket is to represent my time right now.

**Comment by noahmanger** [comment] 2016-09-20 17:31
Next step: replace all links to existing FEC resources.

**Comment by noahmanger** [comment] 2016-09-20 22:56
Another thing we should do if possible to do in an automated way:
Strip the headers in favor of just using the template. 

Every press release has this layout at the top:
![image](https://cloud.githubusercontent.com/assets/1696495/18691756/6dceac42-7f4a-11e6-873d-5ae8c95c0784.png)

This is duplicative of the places the template has for the title, date, and authors.

How much work is it to strip this out and in-so-doing parse the contacts and then set them programmaticaly in the post so they can be displayed correct: 
![image](https://cloud.githubusercontent.com/assets/1696495/18691776/9a869e98-7f4a-11e6-8471-c7768ced454e.png)

If it's easy, I'd say we should do it, but if it's not, it might be easier to just do these by hand for the ones from this year and then call it good.

**Comment by noahmanger** [comment] 2016-10-03 23:20
I'm doing my look through and will file things I catch on this issue. 

On [this page](https://fec-stage-proxy.18f.gov/media/fec-approves-final-rule-on-technical-amendments/) there's an issue with a bunch of nested `blockquotes`. 
![image](https://cloud.githubusercontent.com/assets/1696495/19057268/81f759f6-8983-11e6-9eba-8981469b1a6b.png)

On certain Weekly Digests the PDF links remain ([example](https://fec-stage-proxy.18f.gov/media/week-of-may-16-may-20-2016/))

On older pages (like [this](https://fec-stage-proxy.18f.gov/media/party-fundraising-escalates/)) it looks like `pre` tags are still there. Should we just remove these entirely? 

Also on [older pages,](https://fec-stage-proxy.18f.gov/media/fec-corrects-the-record-regarding-filing-extension/) sometimes text is wrapped in a `<u>` tag which underlines the whole thing or a  or `<font>` tag which is unnecessary. Let's just remove these tags. 

Ok! I think that's it.

**Comment by LindsayYoung** [comment] 2016-10-05 17:34
I think it is the columns rather than block quotes that are throwing that off.

Pre and font should be taken care of, maybe there was a regression. I don't want to over-strip their formatting, some times they wanted the underlines, I did find some cases where there were stray </u> and I removed those.

**Comment by noahmanger** [comment] 2016-10-05 17:40
That blockquote bug is definitely caused by the nested blockquotes, as each one adds 40px of margin on the right and left. 

And yeah, that's fine to not strip all the `<u>` tags. Let's see if we can remove all `<pre>` tags and then that should be fine.

**Comment by LindsayYoung** [comment] 2016-10-05 20:09
I see what you are saying about blockquotes, got rid of those locally.

I think we should have removed all  the pre tags- send me an example if there are some still there.

**Comment by noahmanger** [comment] 2016-10-06 23:30
Closing this as we've now imported these.

**Closed by noahmanger** 2016-10-06 23:30 UTC
Labels: Dashboard: Content migration
