### ISSUE TITLE
Server error when navigating to admin image panel

### ISSUE THREAD

**Issue by noahmanger** [18F/fec-cms#775] opened 2017-01-31 01:57 UTC
Something is broken with the S3 static asset work we merged in earlier. Now going to the `Images` tab in the admin panel yields a 500 error. cc @patphongs @ccostino

**Comment by patphongs** [comment] 2017-01-31 02:52
@ccostino Can you please check if each of the environments (dev, stage, and prod) have these variables set? That might be the problem.

```
CMS_AWS_ACCESS_KEY
CMS_AWS_SECRET_ACCESS_KEY
CMS_AWS_STORAGE_BUCKET_NAME
CMS_AWS_DEFAULT_REGION_NAME
```

**Comment by ccostino** [comment] 2017-01-31 15:15
All three environments do have those set, but I will continue to take a look and see if I can reproduce this locally too.

**Comment by ccostino** [comment] 2017-01-31 19:29
Come to think of it, is it possible that we need to rename these environment variables to not have the `CMS_` in front of them?  The AWS utilities (such as `boto3`) expect the environment variables to be named a certain way (see [AWS CLI Documentation](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-environment) and [`boto3` documentation](https://boto3.readthedocs.io/en/latest/guide/configuration.html#configuring-credentials) around this)

@LindsayYoung, do you happen to know if these were working as they are called now prior to the changes we were working on for the S3 buckets?  Or do you know who might?

**Comment by ccostino** [comment] 2017-02-01 21:41
I am still stuck on this.  At the moment the best I've been able to do is see a 500 response being returned in the CMS logs (e.g., on Staging), but there's no actual error or stack trace being shown either

**Comment by ccostino** [comment] 2017-02-01 22:18
Thanks @LindsayYoung and @patphongs for a couple of leads to look into!  I'm going to continue check connectivity between the CMS and S3, make sure environment variables are being read in and used properly, and that the underlying path is being constructed correctly.

We've ruled out the CORS setup being an issue because that has already been done in all of the S3 buckets and proven to work as demonstrated in the links in https://github.com/18F/fec-proxy/pull/11.

**Comment by ccostino** [comment] 2017-02-02 15:13
Looks like the issue was due to a couple of mis-named environment variable references that I just didn't catch.  I'm sorry about that, and a big thank you to @LindsayYoung for spotting them!

**Comment by patphongs** [comment] 2017-02-02 15:15
major thanks to both of you @ccostino and @LindsayYoung !

**Comment by ccostino** [comment] 2017-02-02 15:28
Final tests show this is okay, closing this issue and moving forward!

**Closed by ccostino** 2017-02-02 15:28 UTC
Labels: Before release, Bug, Dashboard: Content migration, Theme: Infrastructure & tooling, Work: Back-end

**Comment by noahmanger** [comment] 2017-02-02 17:31
Nice work, all!
