### ISSUE TITLE
Design gov delivery sign ups

### ISSUE THREAD

**Issue by AmyKort** [18F/fec-cms#1129] opened 2017-07-11 14:49 UTC
So users can easily set up alerts for the types of FEC activities they want to track, design sign up feature for gov delivery notifications.

What does the sign-up button look like?
What's the next step for a user? Contact gov deliv for help.
What recommendations would gov deliv suggest based on past practice?
How many user work flows will we need?

**Comment by jenniferthibault** [comment] 2017-08-10 21:16
Duplicate of work happening in #1044, closing in favor of that

**Closed by jenniferthibault** 2017-08-10 21:16 UTC
